// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcGDQ8IT29_ikVPgt5VlbrwFQ9e3DIdV4',
    appId: '1:168294486967:web:634530657905c066dbce32',
    messagingSenderId: '168294486967',
    projectId: 'polaku061199',
    authDomain: 'polaku061199.firebaseapp.com',
    databaseURL: 'https://polaku061199-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'polaku061199.appspot.com',
    measurementId: 'G-ZZCQJP153V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC144y5bNpViEVUJZOH5J_R8fJalTEhB8',
    appId: '1:168294486967:android:013177cd0e542963dbce32',
    messagingSenderId: '168294486967',
    projectId: 'polaku061199',
    databaseURL: 'https://polaku061199-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'polaku061199.appspot.com',
  );
}
